spring.application.name=Auth


spring.datasource.url=jdbc:mysql://localhost:3306/amazon_db
spring.datasource.username=root
spring.datasource.password=Sivaram@327

spring.jpa.hibernate.ddl-auto=update



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=toramisetty1993@gmail.com
spring.mail.password=sgxrlkamupuchorm

# enable SMTP authentication and TLS
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

file.upload.images.path=uploads/images/

file.upload.pdf.path=uploads/pdf/

jwt.secret.key=bvcggjjjkkkklluiyfasqwerfccddfghjknbvcd

